[package]
name = "reservist-content"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
reservist-core.workspace = true
serde.workspace = true
serde_json.workspace = true
csv.workspace = true
thiserror.workspace = true

[lints]
workspace = true
